### ISSUE TITLE
Linux Example

### ISSUE THREAD

**Issue by Niondir** [lobaro/FreeRTOS-rust#1]
Since the initial version was developed on Windows, we lack a Linux example.

Pull requests are very welcome.

**Comment by JOE1994** [comment]
Hello :crab: , thank you for sharing this awesome repo :+1:
I see the official [FreeRTOS-Kernel](https://github.com/FreeRTOS/FreeRTOS-Kernel/tree/master/portable) repo doesn't contain the Linux port,
but I found [this repo("**freertos-addons**")](https://github.com/michaelbecker/freertos-addons) that provides a FreeRTOS-Kernel port for Linux (under GPLv2 license).

If there are no conflicts between this repo's license(MIT license) vs. GPLv2 license,
I could try to prepare a PR to create an example for linux
(by using the FreeRTOS-Kernel port for linux from the **freertos-addons** repo).

**Comment by Niondir** [comment]
Thanks. I added a statement to the readme about the license.

**Comment by jdharuman** [comment]
@JOE1994 is New to the Rust program but I am trying to understand the below issue.

I am setting up the FreeRTOS rust for Linux and while building I got an issue with mutable function access for static functions.
I tried to solve but I could not. Any idea how to solve this one?

```c
warning: unnecessary `unsafe` block
  --> freertos-rust-examples/examples/linux/main.rs:11:5
   |
11 |     unsafe {
   |     ^^^^^^ unnecessary `unsafe` block
   |
   = note: `#[warn(unused_unsafe)]` on by default

error[E0596]: cannot borrow immutable static item `FREERTOS_HOOKS` as mutable
  --> freertos-rust-examples/examples/linux/main.rs:12:9
   |
12 |         FREERTOS_HOOKS.set_on_assert(|| { println!("Assert hook called") });
   |         ^^^^^^^^^^^^^^ cannot borrow as mutable
```
