### ISSUE TITLE
Add Cargo features for functionality

### ISSUE THREAD

**Issue by Manishearth** [lobaro/FreeRTOS-rust#10]
Woudl it be possible to add Cargo features for the various bits of functionality? For example, I only want the allocator; otherwise I'm working with a `no_std + alloc` crate.

**Comment by niondir** [comment]
I guess separating some features is a good idea. If it helps you, feel free to provide a pull request.

**Comment by Manishearth** [comment]
https://github.com/lobaro/FreeRTOS-rust/pull/12
