### ISSUE TITLE
bound `P: AsRef<Path>` for heap in freertos-cargo-build cannot infer type for string argument

### ISSUE THREAD

**Issue by apullin** [lobaro/FreeRTOS-rust#11]
I am trying to build this package with the latest nightly, and I am getting the following error:

```
error[E0282]: type annotations needed
 --> build.rs:8:7
  |
8 |     b.heap("heap_4.c".to_string());              // Set the heap_?.c allocator to use from
  |       ^^^^ cannot infer type for type parameter `P` declared on the associated function `heap`

error: aborting due to previous error
```

Notably, in my `build.rs`, I made the modification of explicit String conversion, otherwise I get a cargo error about mismatched types:
`b.heap("heap_4.c".to_string() );`

Relaxing the signature to: `pub fn heap(&mut self, file_name: String)`
appears to resolve the build issue, although that is just a guess, and other regressions may be introduced.

**Comment by niondir** [comment]
Thanks for working this out. A pull request is very welcome.

**Comment by niondir** [comment]
Thanks a lot.
