### ISSUE TITLE
Working Cortex-M4 example 

### ISSUE THREAD

**Issue by tstellanova** [lobaro/FreeRTOS-rust#2]
Hello, I've got a simple [LED blinking example with two tasks and queue / message passing](https://github.com/tstellanova/pumpk)

This runs on stm32f303 (Cortex M4) hardware, specifically on the low-cost [Robotdyn mini-M4](https://crates.io/crates/stm32f303cct6-robotdyn-bsp)

What's the best way to integrate this with the examples in _this_ repo? I noticed that the Cortex-M3 example has a bunch of comments indicating the example is not functional.

**Comment by Niondir** [comment]
My problem with the cortex M3 was that I had no debugger running. You are very welcome to provide an Cortex M4 example. The M3 example might be a good starting point, even if some issues still need a fix. 
I will give my very best to help with concrete questions.

Just fork this repo and when we get it running or even close to running I'm open for a pull request.

Kind regards,
Tobias

**Comment by Niondir** [comment]
I you don't mind I would also link your repo in the readme of this project.

**Comment by tstellanova** [comment]
> My problem with the cortex M3 was that I had no debugger running. You are very welcome to provide an Cortex M4 example. The M3 example might be a good starting point, even if some issues still need a fix.
> I will give my very best to help with concrete questions.
> 
> Just fork this repo and when we get it running or even close to running I'm open for a pull request.
> 
> Kind regards,
> Tobias

Sounds good, I'll try to figure out the right way to integrate it.
