### ISSUE TITLE
Use FreeRtosSemaphoreHandle for semaphore functions

### ISSUE THREAD

**Issue by schteve** [lobaro/FreeRTOS-rust#54]
`shim.rs` has a bunch of semaphore functions that use `FreeRtosQueueHandle` instead of `FreeRtosSemaphoreHandle`. It's the same underlying type so it should be a non-functional change to switch over.

Also review other types to see if there are others that could be improved.

**Comment by agerasev** [comment]
Opened a PR for semaphore and mutex functions: #56
