### ISSUE TITLE
Unable to disable `vAssertCalled`

### ISSUE THREAD

**Issue by pileghoff** [lobaro/FreeRTOS-rust#62]
I already have an implementation of `vAssertCalled` in C, and because would like to disable the implementation in this create, but have not found a way.

I tried removing the `hooks` feature, but it turns out that `vAssertCalled` is defined anyway. Is this intentional?

**Comment by niondir** [comment]
https://github.com/lobaro/FreeRTOS-rust/blob/master/freertos-rust-examples/examples/nrf9160/FreeRTOSConfig.h

configASSERT ist part of the freertos config and defines the assert method. You can just use another method name and rename your implementation with your freertos config.

Does this helps you?

**Comment by pileghoff** [comment]
Yeah, that works, but I still find it strange that the library provides an assert hook using the "default" name, instead of leaving it up to the application.

**Comment by niondir** [comment]
We could rename the default implementation provided here and change the define in the examples.

I would be fine with that.
